enum CodeError {
    TOKEN_HEADER_EMPTY,
    TOKEN_VERIFY_FAILED,
    USER_INFORMATION_EMPTY,
    BODY_PROPERTY_EMPTY,
    PROPERTY_RATE_GREATER_THAN_5,
    PARAM_WRONG_FORMAT,
    PRODUCT_NOT_FOUND,
    PRODUCT_NOT_PURCHASED,
    BODY_PROPERTY_WRONG_FORMAT,
}

export default CodeError;